Own http headers
wearereasonablepeople/ApiConnector pull request #50
Opened 2017-03-27 15:29 UTC by syllerim

Closes #45

2017-03-27 15:31 UTC, alickbass requested changes
Please resolve git conflicts by rebasing your branch on top of master

2017-03-28 07:56 UTC, alickbass requested changes

2017-03-28 07:56 UTC, alickbass commented on ApiConnectorTests/TestHTTP.swift
> +    func testHTTHeader() {
To be honest, I think that this test is a bit useless, as it tests `Dictionary`, which we know is working. So I think that you can remove completely this method

2017-03-28 07:56 UTC, alickbass commented on ApiConnectorTests/TestHTTP.swift
> +        result = HTTP.Header.toStringKeys(headers: headers)
You can just write
```swift
let result = HTTP.Header.toStringKeys(headers: headers)
```

2017-03-28 07:56 UTC, alickbass commented on ApiConnectorTests/TestHTTP.swift
> +        XCTAssertEqual(headers[.contentType], result[HTTP.Header.Key.contentType.rawValue])
I would use the result from previous method:
```swift 
let result = [HTTP.Header.Key.accept.rawValue: "application/json" ,
                     HTTP.Header.Key.acceptLanguage.rawValue: "en-US",
                     HTTP.Header.Key.contentType.rawValue: "charset=utf-8"]
```

and the just compared 2 dictionaries:

```swift
XCTAssertEqual(result, HTTP.Header.toStringKeys(headers: headers))
```

2017-03-28 07:56 UTC, alickbass commented on ApiConnector/HTTP.swift
> +        self.init(stringLiteral: value)
This method is not covered with tests. For the example of how to cover such cases, take a look [here](https://github.com/Jitsusama/UInt128/blob/master/tests/UInt128Tests.swift) at line 147

2017-03-28 07:56 UTC, alickbass commented on ApiConnector/HTTP.swift
> +        self.init(stringLiteral: value)
This method is not covered with tests. For the example of how to cover such cases, take a look [here](https://github.com/Jitsusama/UInt128/blob/master/tests/UInt128Tests.swift) at line 141

2017-03-28 08:01 UTC, syllerim commented on ApiConnectorTests/TestHTTP.swift
> +        result = HTTP.Header.toStringKeys(headers: headers)
yeah, this is nonsense

2017-03-28 08:07 UTC, alickbass commented on ApiConnectorTests/TestHTTP.swift
> +        let headers: [HTTP.Header.Key: String] = [.accept: "application/json" ,
BTW, here you can do like this:
```swift
let headers: HTTP.Headers = ....
```

2017-03-28 08:22 UTC, alickbass commented on ApiConnectorTests/ApiConnectionTests.swift
> +        let header: [HTTP.Header.Key: String] = [.accept: "application/json"]
Here use can also change to:

```swift
let headers: HTTP.Headers = ...
```

2017-03-28 08:23 UTC, alickbass commented on ApiConnectorTests/ApiConnectionTests.swift
> +        XCTAssertEqual(request.allHTTPHeaderFields?[HTTP.Header.Key.accept.rawValue], headerToString[HTTP.Header.Key.accept.rawValue])
Here you can just do:
```swift
XCTAssertEqual(request.allHTTPHeaderFields?, headersToString)
```

2017-03-28 08:25 UTC, alickbass commented
Can you please rename the file from `TestHTTP` to `HTTPTests` to be consistent with other tests

2017-03-28 08:47 UTC, syllerim commented on ApiConnector/HTTP.swift
> +        self.init(stringLiteral: value)
Implemented

2017-03-28 08:47 UTC, syllerim commented on ApiConnector/HTTP.swift
> +        self.init(stringLiteral: value)
Implemented

2017-03-28 08:52 UTC, alickbass requested changes

2017-03-28 08:52 UTC, alickbass commented on ApiConnectorTests/HTTPTest.swift
> +        XCTAssertEqual(HTTP.Header.Key(extendedGraphemeClusterLiteral: "22").rawValue, "\u{00032}\u{00032}")
Should be the other way around here:
```swift
HTTP.Header.Key(extendedGraphemeClusterLiteral: "\u{00032}\u{00032}").rawValue, "22"
```

2017-03-28 08:52 UTC, alickbass commented on ApiConnectorTests/HTTPTest.swift
> +//  TestHTTP.swift
Can you please rename the file t `HTTPTests` instead of `HTTPTest`

2017-03-28 09:01 UTC, syllerim commented on ApiConnectorTests/HTTPTest.swift
> +//  TestHTTP.swift
sure

2017-03-28 09:03 UTC, syllerim commented on ApiConnectorTests/HTTPTest.swift
> +        XCTAssertEqual(HTTP.Header.Key(extendedGraphemeClusterLiteral: "22").rawValue, "\u{00032}\u{00032}")
sure

2017-03-28 09:13 UTC, alickbass approved these changes

2017-03-28 09:14 UTC, merged